### PR TITLE
postgres: Introduce indexes validity check

### PR DESCRIPTION
**Pull request by abeglu**

### CODE REVIEW

**Comment by kofrezo** [comment]
We have this check already: 
```
$ mon -c postgres_invalid_indexes_eu1_game
postgres_invalid_indexes_eu1_game - OK - All indexes are valid
```

**Comment by abeglu** [comment]
Currently, we're creating a separate command for each database, but by using this script, we can check multiple databases with a single command.

**Review by seqizz — CHANGES_REQUESTED** [review]
I guess single check is a lot cleaner on monitoring side, so LGTM. But please process this with a formatter like ruff. We should start using f-strings at least at this point.

**Review by seqizz — APPROVED** [review]
Tested, sadly (or thankfully) there was no easy way to test actual invalid case.

**Pull request merged**
